version: '3'

networks:
  internal:

services:
    frontend:
      image: cwalops/frontend:init
      ports:
        - "5000:5000"
      networks:
        internal:
          aliases:
            - frontend

    ratioservice:
      image: cwalops/ratioservice:init
      ports:
        - "5001:5001"
      networks:
        internal:
          aliases:
            - ratioservice

    detailservice:
      image: cwalops/detailservice:init
      ports:
        - "5002:5002"
      networks:
        internal:
          aliases:
            - detailservice
