version: '3'
services:

    frontend:
      image: cwalops/frontend:init
      ports:
        - "5000:5000"
        
    detailservice:
      image: cwalops/detailservice:init
      ports:
        - "5001:5001"
        
    ratioservice:
      image: cwalops/ratioservice:init
      ports:
        - "5002:5002"
        
    