apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: detailservice
    app: detailservice
  name: detailservice
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: detailservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        app: detailservice
        io.kompose.network/internal: "true"
        io.kompose.service: detailservice
    spec:
      containers:
      - image: cwalops/detailservice:latest
        name: detailservice
        ports:
        - containerPort: 5002
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      restartPolicy: Always
status: {}
